name: Build & Release Taiko-Master

on:
  workflow_dispatch:


# 权限配置，确保 GITHUB_TOKEN 有权限发布 release
permissions:
  contents: write


jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # 1. 拉取仓库代码
      - name: Checkout 源码
        uses: actions/checkout@v3

      # 2. 安装 Python
      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. 安装依赖
      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4. 使用 PyInstaller 打包 .exe
      - name: 打包 EXE
        run: |
          pyinstaller --onefile "Taiko Master.py"

      # 5. 创建 Release
      - name: 创建 Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name || 'v0.0.0-manual' }}
          release_name: Release ${{ github.ref_name || github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. 上传 EXE 到 Release
      - name: 上传 EXE 到 Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./dist/Taiko Master.exe"
          asset_name: Taiko-Master-${{ github.ref_name || github.run_number }}.exe
          asset_content_type: application/octet-stream
