name: Build & Release Taiko-Master

# 既监听符合 vX.Y.Z 的 tag 推送，也支持手动触发
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    # Windows 环境以生成 .exe
    runs-on: windows-latest

    steps:
      # 1. 拉取仓库代码
      - name: Checkout 源码
        uses: actions/checkout@v3

      # 2. 安装 Python（示例用 Python+PyInstaller 打包）
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. 安装依赖并安装 PyInstaller
      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4. 调用 PyInstaller 打包成单文件 EXE
      - name: 用 PyInstaller 打包 EXE
        run: |
          pyinstaller --onefile "Taiko Master.py"
        # 输出：dist/Taiko Master.exe

      # 5. 创建（或更新）GitHub Release
      - name: 创建 Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name || 'v0.0.0-manual' }}
          release_name: Release ${{ github.ref_name || github.run_number }}
          draft: false       # 直接发布，不做草稿
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. 上传 EXE 到刚创建的 Release
      - name: 上传 EXE 到 Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/"Taiko Master.exe"
          asset_name: Taiko-Master-${{ github.ref_name || github.run_number }}.exe
          asset_content_type: application/octet-stream
